- name: move c:\ directory backup.
  win_copy:
    src: "{{ zbx_dir }}"
    dest: "{{ zbx_dir }}_backup"
    remote_src: yes
  ignore_errors: True
  
- name: Delete the moment file.
  win_file:
    path: "{{ zbx_dir }}"
    state: absent
  ignore_errors: True

- name:  Put Executed file to remote host.
  win_copy:
    src: "{{ bin_tar_name }}"
    dest: "c:\\{{ bin_tar_name }}"

- name: Unarchive the exc file to the target directory.
  win_unzip:
    creates: "{{ zbx_dir }}"
    src: "c:\\{{ bin_tar_name}}"
    dest: "{{ zbx_dir }}"
    
- name: Move Binary file to workdir.
  win_copy:
    remote_src: yes
    src: "{{ zbx_dir }}\\{{ tar_exe_path }}"
    dest: "{{ zbx_dir }}\\zabbix_agentd.exe"

- name: Remove Binary Directory.
  win_file:
    path: "{{ zbx_dir }}\\bin"
    state: absent

- name: Remove tar package.
  win_file:
    path: "c:\\{{ bin_tar_name }}"
    state: absent

- name: Remove Conf directory.
  win_file:
    path: "{{ zbx_dir }}\\conf"
    state: absent

- name:  Put configure  file to remote host.
  win_template:
    src: zabbix_agentd.win.conf.j2
    dest: "{{ zbx_dir }}/zabbix_agentd.win.conf"

- name: Install zabbix agent on the host
  win_command: powershell.exe
  args:
    stdin: "{{ zbx_dir }}/zabbix_agentd.exe -c {{ zbx_dir }}/zabbix_agentd.win.conf -i"
    
- name: Start zabbix agent on the host
  win_command: powershell.exe
  args:
    stdin: "{{ zbx_dir }}/zabbix_agentd.exe -c {{ zbx_dir }}/zabbix_agentd.win.conf -s"
