bin_tar_name: zabbix_agent.tar.gz #二进制格式安装包名
src_tar_name: zabbix_server.tar.gz #源代码编译安装 包名
tmp_dir: "/tmp/zabbix"   # 源码代码编译安装临时编译目录

# src | bin
ins_method: bin  # 安装方式
myflag: centos  #标识 客户端
server: 192.168.5.11  # zabbix server IP
zbx_dir: /usr/local/zabbix  # 安装路径

init_etc_file: /usr/local/etc/zabbix_agentd  #Centos 6 配置文件路径
src_etc_file: etc/zabbix_agentd.conf  # 源代码配置文件路径 以下都是Centos 7方式
bin_etc_file: conf/zabbix_agentd.conf # 二进制配置文件路径 

