- name: Turn off firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no 
    when ansible_distribution_major_version="7"

- name: Turn off Selinux by the cmdline.
  shell: setenforce 0

- name: Turn off Selinux
  shell: sed -i s/SELINUX=enforcing/SELINUX=disabled/ /etc/selinux/config

- name: Add user for zabbix.
  shell: useradd -M zabbix
  when ansible_env.USER="root"
